package nay.amethyst.simulation.movement;

public enum MovementInputFlag {
    HORIZONTAL_COLLISION,
    VERTICAL_COLLISION,
    START_FLYING,
    STOP_FLYING,
    SNEAKING,
    SPRINT_DOWN,
    START_SPRINTING,
    STOP_SPRINTING,
    START_SNEAKING,
    STOP_SNEAKING,
    START_SWIMMING,
    STOP_SWIMMING,
    START_CRAWLING,
    STOP_CRAWLING,
    SNEAK_DOWN,
    START_JUMPING,
    JUMPING,
    START_GLIDING,
    STOP_GLIDING,
    JUMP_PRESSED_RAW,
    AUTO_JUMPING_IN_WATER
}
