name: Amethyst
main: nay.amethyst.AmethystPlugin
version: "1.1.7"
api: ["3.0.0"]
author: Nay
description: Server-authoritative anti-cheat for PowerNukkitX.
commands:
  amethyst:
    description: Manage Amethyst.
    usage: "/amethyst <status|reload|alerts>"
    permission: amethyst.alerts
permissions:
  amethyst.alerts:
    description: Receives alerts and allows use of the Amethyst command.
    default: op
  amethyst.bypass:
    description: Bypasses Amethyst checks.
    default: false
